INSERT INTO medicos (nome, email, crm, especialidade, logradouro, bairro, cep, complemento, numero, uf, cidade)
VALUES
    ('Dr. Ana Cardio', 'ana.cardio@example.com', 'CRM001', 'CARDIOLOGISTA', 'Rua das Flores', 'Centro', '12345-678', 'Apto 101', '10', 'SP', 'São Paulo'),
    ('Dra. Bianca Gineco', 'bianca.gineco@example.com', 'CRM002', 'GINECOLOGISTA', 'Av. Paulista', 'Bela Vista', '23456-789', 'Sala 2', '20', 'SP', 'São Paulo'),
    ('Dr. Carlos Clinico', 'carlos.clinico@example.com', 'CRM003', 'CLINICO_GERAL', 'Rua dos Jacarandás', 'Jardim Primavera', '34567-890', 'Bloco B', '50', 'RJ', 'Rio de Janeiro'),
    ('Dra. Daniela Dentista', 'daniela.dentista@example.com', 'CRM004', 'DENTISTA', 'Rua das Palmeiras', 'Centro', '45678-901', 'Casa 3', '5', 'MG', 'Belo Horizonte'),
    ('Dr. Eduardo Cardio', 'eduardo.cardio@example.com', 'CRM005', 'CARDIOLOGISTA', 'Rua dos Lírios', 'Centro', '56789-012', NULL, '15', 'SP', 'Campinas'),
    ('Dra. Fernanda Gineco', 'fernanda.gineco@example.com', 'CRM006', 'GINECOLOGISTA', 'Av. Rio Branco', 'Jardim Europa', '67890-123', 'Apto 202', '30', 'RJ', 'Rio de Janeiro'),
    ('Dr. Gabriel Clinico', 'gabriel.clinico@example.com', 'CRM007', 'CLINICO_GERAL', 'Rua das Acácias', 'Centro', '78901-234', 'Bloco A', '40', 'MG', 'Belo Horizonte'),
    ('Dra. Helena Dentista', 'helena.dentista@example.com', 'CRM008', 'DENTISTA', 'Av. Brasil', 'Jardim América', '89012-345', 'Sala 1', '60', 'SP', 'São Paulo'),
    ('Dr. Igor Cardio', 'igor.cardio@example.com', 'CRM009', 'CARDIOLOGISTA', 'Rua dos Pinheiros', 'Centro', '90123-456', 'Cobertura', '20', 'RJ', 'Rio de Janeiro'),
    ('Dra. Juliana Gineco', 'juliana.gineco@example.com', 'CRM010', 'GINECOLOGISTA', 'Av. das Nações', 'Bela Vista', '01234-567', 'Loft 3', '70', 'MG', 'Belo Horizonte'),
    ('Dr. Lucas Clinico', 'lucas.clinico@example.com', 'CRM011', 'CLINICO_GERAL', 'Rua das Magnólias', 'Jardim Botânico', '12345-678', 'Apto 303', '80', 'SP', 'São Paulo'),
    ('Dra. Marina Dentista', 'marina.dentista@example.com', 'CRM012', 'DENTISTA', 'Av. Paulista', 'Jardim Paulista', '23456-789', 'Bloco C', '90', 'RJ', 'Rio de Janeiro'),
    ('Dr. Nelson Cardio', 'nelson.cardio@example.com', 'CRM013', 'CARDIOLOGISTA', 'Rua dos Cedros', 'Centro', '34567-890', NULL, '100', 'MG', 'Belo Horizonte'),
    ('Dra. Olivia Gineco', 'olivia.gineco@example.com', 'CRM014', 'GINECOLOGISTA', 'Av. das Palmeiras', 'Jardim das Acácias', '45678-901', 'Casa 5', '110', 'SP', 'Campinas'),
    ('Dr. Paulo Clinico', 'paulo.clinico@example.com', 'CRM015', 'CLINICO_GERAL', 'Rua dos Jasmins', 'Bela Vista', '56789-012', 'Bloco A', '120', 'RJ', 'Rio de Janeiro'),
    ('Dra. Quésia Dentista', 'quesia.dentista@example.com', 'CRM016', 'DENTISTA', 'Av. Paulista', 'Centro', '67890-123', 'Cobertura', '130', 'MG', 'Belo Horizonte'),
    ('Dr. Rafael Cardio', 'rafael.cardio@example.com', 'CRM017', 'CARDIOLOGISTA', 'Rua das Orquídeas', 'Jardim América', '78901-234', NULL, '140', 'SP', 'São Paulo'),
    ('Dra. Sara Gineco', 'sara.gineco@example.com', 'CRM018', 'GINECOLOGISTA', 'Av. Rio Branco', 'Centro', '89012-345', 'Sala 1', '150', 'RJ', 'Rio de Janeiro'),
    ('Dr. Tiago Clinico', 'tiago.clinico@example.com', 'CRM019', 'CLINICO_GERAL', 'Rua das Hortênsias', 'Bela Vista', '90123-456', 'Bloco C', '160', 'MG', 'Belo Horizonte'),
    ('Dra. Ursula Dentista', 'ursula.dentista@example.com', 'CRM020', 'DENTISTA', 'Av. Brasil', 'Jardim Botânico', '01234-567', NULL, '170', 'SP', 'São Paulo');
